# Generated by Django 3.0.6 on 2020-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='owner',
        ),
    ]
